# redis 相关
spring:
  redis:
    # host: ktp-redis
    host: 192.168.209.128
    # host: 127.0.0.1
    port: 6379
    password: P$T3FSxJ0ioqi6AB

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/life_management?characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bob
    password: 123456
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

server:
  port: 8801

mybatis:
  type-aliases-package: com.gov.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers:
    - com.gov.base.MyMapper
  not-empty: false
  identity: MYSQL
  before: true

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

# feign 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true