server:
  port: 8810
spring:
  redis:
    # host: ktp-redis
    host: 192.168.209.128
    # host: 127.0.0.1
    port: 6379
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/p_code_repository?characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bob
    password: 123456
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
  rabbitmq:
    #host: 172.18.225.161
    # host: ktp-rabbitmq
    host: 127.0.0.1
    port: 5672
    username: rq_gov
    password: 9cddMNMbaRscd2wE
    listener:
      simple:
        default-requeue-rejected: false
        acknowledge-mode: auto
        retry:
          enabled: false

mybatis:
  type-aliases-package: com.gov.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers:
    - com.dxs.distribute.lock.mapper
  not-empty: false
  identity: MYSQL
  before: true

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

gov-delay:
  queue:
    queues:
      synCountryDelayRetry:
        queue: gov_syn_country_store_code_queue
        topic: gov.syn.country.store.code
        exchange: gov_syn_country_store_code_topic
        delay-time: 3000
        multiplier: 2